# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('codigo', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('fecnac', models.DateField()),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nivel', models.CharField(max_length=40)),
                ('descripcion', models.TextField(blank=True, max_length=100, null=True)),
                ('desde', models.IntegerField()),
                ('hasta', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('desde', models.IntegerField()),
                ('hasta', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Dimension',
                'verbose_name_plural': 'Dimensiones',
            },
        ),
        migrations.CreateModel(
            name='Eap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Eap',
                'verbose_name_plural': 'Eaps',
            },
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Eje',
                'verbose_name_plural': 'Ejes',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_pre', models.IntegerField()),
                ('res_post', models.IntegerField()),
                ('recomendaciones', models.TextField(max_length=200)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Alumno')),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Dimension')),
            ],
            options={
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('sede', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('eap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Eap')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_test', models.CharField(max_length=40)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('eje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Eje')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Periodo'),
        ),
        migrations.AddField(
            model_name='eap',
            name='falcultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Facultad'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Test'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Test'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Grupo'),
        ),
    ]
